env = Environment()

env['CXX'] = 'g++'
env.Append(CCFLAGS=['-pthread', '-Wall', '-O1', '-std=c++11'],
           CPPPATH=['/opt/cantera/include', '.'],
           LIBS=['cantera', 'sundials_cvodes', 'sundials_ida', 'sundials_nvecserial', 'blas', 'lapack'],
           LIBPATH=['/opt/cantera/lib'],
           LINKFLAGS=['-pthread'],
           FRAMEWORKS=[])

program = env.Program('counterflowDiffusionFlame', 'counterflowDiffusionFlame.cpp')
Default(program)
