env = Environment()

env['CXX'] = 'g++'
env.Append(CCFLAGS=['-pthread', '-O0', '-g', '-std=c++0x'],
           CPPPATH=['/opt/cantera/include','./src'],
           LIBS=['cantera', 'sundials_cvodes', 'sundials_ida', 'sundials_nvecserial', 'blas', 'lapack'],
           LIBPATH=['/opt/cantera/lib'],
           LINKFLAGS=['-pthread'],
           FRAMEWORKS=[])

program = env.Program('./bin/counterflowSprayFlame', ['./src/counterflowSprayFlame.cpp','./src/Lagrangian.cpp', './src/StFlowSpr.cpp', './src/Sim1DSpr.cpp', './src/OneDimSpr.cpp'])
Default(program)
